import type { MaterialId, MaterialPreset } from "./types";

/**
 * PBR tuning presets per material family. Applied on top of a part's base
 * color by cloning the source `MeshPhysicalMaterial` and overwriting these
 * scalar properties — texture maps from the original GLB are preserved.
 */
export const MATERIAL_PRESETS: Record<MaterialId, MaterialPreset> = {
  leather: {
    id: "leather",
    label: "Leather",
    description: "Full-grain leather with a soft satin sheen.",
    roughness: 0.42,
    metalness: 0,
    clearcoat: 0.12,
    clearcoatRoughness: 0.35,
    sheen: 0,
    sheenRoughness: 1,
    envMapIntensity: 1,
    priceModifier: 0,
  },
  suede: {
    id: "suede",
    label: "Suede",
    description: "Soft napped leather with a velvety, light-diffusing surface.",
    roughness: 1,
    metalness: 0,
    clearcoat: 0,
    clearcoatRoughness: 0,
    sheen: 1,
    sheenRoughness: 0.55,
    envMapIntensity: 0.4,
    priceModifier: 25,
  },
  mesh: {
    id: "mesh",
    label: "Mesh",
    description: "Lightweight breathable mesh with a subtle textile sheen.",
    roughness: 0.85,
    metalness: 0,
    clearcoat: 0,
    clearcoatRoughness: 0,
    sheen: 0.35,
    sheenRoughness: 0.85,
    envMapIntensity: 0.6,
    priceModifier: 0,
  },
  knit: {
    id: "knit",
    label: "Knit",
    description: "Engineered knit textile with fine woven texture.",
    roughness: 0.92,
    metalness: 0,
    clearcoat: 0,
    clearcoatRoughness: 0,
    sheen: 0.45,
    sheenRoughness: 0.75,
    envMapIntensity: 0.5,
    priceModifier: 15,
  },
  rubber: {
    id: "rubber",
    label: "Rubber",
    description: "Durable molded rubber with a low-gloss finish.",
    roughness: 0.65,
    metalness: 0,
    clearcoat: 0.2,
    clearcoatRoughness: 0.45,
    sheen: 0,
    sheenRoughness: 1,
    envMapIntensity: 0.8,
    priceModifier: 0,
  },
  "glossy-plastic": {
    id: "glossy-plastic",
    label: "Glossy Plastic",
    description: "High-gloss polymer with crisp specular reflections.",
    roughness: 0.08,
    metalness: 0,
    clearcoat: 1,
    clearcoatRoughness: 0.04,
    sheen: 0,
    sheenRoughness: 1,
    envMapIntensity: 1.4,
    priceModifier: 20,
  },
  matte: {
    id: "matte",
    label: "Matte Finish",
    description: "Flat, non-reflective finish for a stealth aesthetic.",
    roughness: 1,
    metalness: 0,
    clearcoat: 0,
    clearcoatRoughness: 0,
    sheen: 0,
    sheenRoughness: 1,
    envMapIntensity: 0.5,
    priceModifier: 10,
  },
};

export const MATERIAL_ORDER: MaterialId[] = [
  "leather",
  "suede",
  "mesh",
  "knit",
  "rubber",
  "glossy-plastic",
  "matte",
];
